### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by mukesh-panigrahi**
/woof

### CODE REVIEW

**Comment by mukesh-panigrahi** [comment]
@mukesh-panigrahi: [dog image](https://random.dog/cb0e48cd-2ffa-457c-99ad-cb95722bdde8.gif)

<details>

In response to [this](https://github.com/mukesh-org/source-repo/pull/14):

>/woof


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by mukesh-panigrahi** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mukesh-org/source-repo/pull/14#" title="Author self-approved">mukesh-panigrahi</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/mukesh-org/source-repo/blob/master/OWNERS)~~ [mukesh-panigrahi]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by mukesh-panigrahi** [comment]
@mukesh-panigrahi: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/mukesh-org/source-repo/pull/14#issuecomment-453515120):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by pratikmm — COMMENTED** [review]
/lgtm

**Comment by mukesh-panigrahi** [comment]
LGTM label has been added.  <details>Git tree hash: d6d4a53db5dfb2c8d583b86831bd9025226afe1f</details>

**Comment by mukesh-panigrahi** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/mukesh-org/source-repo/pull/14#" title="Author self-approved">mukesh-panigrahi</a>*, *<a href="https://github.com/mukesh-org/source-repo/pull/14#issuecomment-453515366" title="Approved">pratikmm</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/mukesh-org/source-repo/blob/master/OWNERS)~~ [mukesh-panigrahi,pratikmm]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
